---
- name: 'ensure log_host is defined'
  assert:
    that: "'{{ log_host }}' is defined"
  tags:
    - rsyslog

- name: 'ensure package rsyslog is installed'
  yum:
    name: rsyslog
    state: installed
  notify: remove sysklogd
  tags:
    - rsyslog

- name: 'copy /etc/rsyslog.conf file for normal host'
  template:
    src: etc-rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0600
  notify: restart rsyslog
  tags:
    - rsyslog

- name: 'rewrite /etc/rsyslog.conf file for remote loghost'
  template:
    src: etc-rsyslog.loghost.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0600
  when: is_monitor|bool
  notify: restart rsyslog
  tags:
    - rsyslog

- name: 'copy /etc/sysconfig/rsyslog file'
  template:
    src: etc-sysconfig-rsyslog.j2
    dest: /etc/sysconfig/rsyslog
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog
  tags:
    - rsyslog

- name: 'enable rsyslog'
  service:
    name: rsyslog
    enabled: true
  notify: restart rsyslog
  tags:
    - rsyslog

- name: 'restart rsyslog if needed'
  meta: flush_handlers

- name: 'ensure permissions on all logfiles are configured'
  file:
    path: /var/log
    mode: 'g-wx,o-rwx'
    recurse: true
  tags:
    - compliance
    - rsyslog
    - permissions

- name: 'ensure permissions are correct on wtmp'
  file:
    path: /var/log/wtmp
    mode: 0640
  tags:
    - compliance
    - rsyslog
    - permissions

- name: 'ensure permissions are correct on dmesg'
  file:
    path: /var/log/dmesg
    mode: 0640
  ignore_errors: true
  tags:
    - compliance
    - rsyslog
    - permissions
