---
- name: 'Ensure log_host is defined'
  assert:
    that: "'{{ log_host }}' is defined"
  tags:
    - rsyslog

- name: 'Ensure package rsyslog is installed'
  yum:
    name: rsyslog
    state: installed
  notify: Remove sysklogd
  tags:
    - rsyslog

- name: 'Copy /etc/rsyslog.conf file for normal host'
  template:
    src: etc-rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0600
    validate: 'rsyslogd -N1 -f %s'
  notify: Restart rsyslog
  tags:
    - rsyslog

- name: 'Rewrite /etc/rsyslog.conf file for remote loghost'
  template:
    src: etc-rsyslog.loghost.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0600
  when: is_monitor|bool
  notify: Restart rsyslog
  tags:
    - rsyslog

- name: 'Copy /etc/sysconfig/rsyslog file'
  template:
    src: etc-sysconfig-rsyslog.j2
    dest: /etc/sysconfig/rsyslog
    owner: root
    group: root
    mode: 0644
  notify: Restart rsyslog
  tags:
    - rsyslog

- name: 'Enable rsyslog'
  service:
    name: rsyslog
    enabled: true
  notify: Restart rsyslog
  tags:
    - rsyslog

- name: 'Restart rsyslog if needed'
  meta: flush_handlers

- name: 'Ensure permissions on all logfiles are configured'
  file:
    path: /var/log
    mode: 'g-wx,o-rwx'
    recurse: true
  tags:
    - compliance
    - rsyslog
    - permissions

- name: 'Ensure permissions are correct on wtmp'
  file:
    path: /var/log/wtmp
    mode: 0640
  tags:
    - compliance
    - rsyslog
    - permissions

- name: 'Ensure permissions are correct on dmesg'
  file:
    path: /var/log/dmesg
    mode: 0640
    state: touch
  changed_when: false
  tags:
    - compliance
    - rsyslog
    - permissions
