---

- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reexec  # noqa: command-instead-of-module
  changed_when: true

- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
...
